# Generated by Django 2.2.5 on 2019-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('magic_key', models.CharField(help_text='The magic key', max_length=128)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
